fix(mailviewer): Load HTML view faster by pre-caching it
runbox/runbox7 pull request #1003
Opened 2021-05-27 10:56 UTC by castaway

Fixes (hopefully) #998

2021-05-27 11:57 UTC, tadzik requested changes

2021-05-27 11:57 UTC, tadzik commented on src/app/mailviewer/singlemailviewer.component.ts
> +          console.log('markSeen pre');
Leftovers :)

2021-05-27 11:57 UTC, tadzik commented
Looks good apart of the leftover logs :)

2021-05-27 21:10 UTC, gtandersen approved these changes
Great, @castaway!

2021-06-01 09:38 UTC, castaway commented on src/app/mailviewer/singlemailviewer.component.ts
> +          console.log('markSeen pre');
fixed

2021-06-02 14:58 UTC, tadzik approved these changes

2021-06-02 17:48 UTC, merged