fix(draft): Add distinctUntilChanged for auto save
runbox/runbox7 pull request #1465
Opened 2023-07-03 10:33 UTC by antoniskalou

This should reduce the likelyhood that a draft will be saved after it has been sent.

See https://github.com/runbox/runbox7/issues/644

2023-07-03 22:58 UTC, perigrin approved these changes
This looks reasonable now that I've looked at the docs for `distinctUntilChanged()`.

2023-07-10 16:19 UTC, castaway commented
Hmm, dUC uses "===" by default, is that doing to dwim? https://www.learnrxjs.io/learn-rxjs/operators/filtering/distinctuntilchanged 

Might need to check the fields, eg like https://github.com/runbox/runbox7/blob/master/src/app/rmmapi/messagelist.service.ts#L79

2023-07-19 12:07 UTC, castaway requested changes
Couple of minor updates please ;)

2023-07-19 12:07 UTC, castaway commented on src/app/common/util.ts
> +// Copyright (C) 2016-2018 Runbox Solutions AS (runbox.com).
2023!

2023-07-19 12:07 UTC, castaway commented on src/app/common/util.spec.ts
> +// Copyright (C) 2016-2018 Runbox Solutions AS (runbox.com).
2023!

2023-07-19 12:07 UTC, castaway commented on src/app/common/util.spec.ts
> +    it('objectEqual', () => {
Slightly more descriptive test names please?

2023-07-24 10:21 UTC, castaway approved these changes
lgtm

2023-07-24 10:22 UTC, merged